proxy-groups:
  - name: èŠ‚ç‚¹é€‰æ‹©
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - ä¸­è½¬åŠ é€Ÿ
      - ç›´è”èŠ‚ç‚¹    
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ¬§æ´²èŠ‚ç‚¹
      - ç¾æ´²èŠ‚ç‚¹
      - æ¾³æ´²èŠ‚ç‚¹
      - å…¶ä»–èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢ 
      - DIRECT
      
  - name: æ‰‹åŠ¨åˆ‡æ¢
    icon: https://testingcf.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select
    
  - name: ç”µæŠ¥æ¶ˆæ¯
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    proxies:
      - èŠ‚ç‚¹é€‰æ‹©
      - ä¸­è½¬åŠ é€Ÿ
      - ç›´è”èŠ‚ç‚¹    
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ¬§æ´²èŠ‚ç‚¹
      - ç¾æ´²èŠ‚ç‚¹
      - æ¾³æ´²èŠ‚ç‚¹
      - å…¶ä»–èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢ 
      
  - name: OpenAI
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    type: select
    proxies:
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ¬§æ´²èŠ‚ç‚¹
      - ç¾æ´²èŠ‚ç‚¹
      - æ¾³æ´²èŠ‚ç‚¹
      - å…¶ä»–èŠ‚ç‚¹
      - èŠ‚ç‚¹é€‰æ‹©
      - ä¸­è½¬åŠ é€Ÿ
      - ç›´è”èŠ‚ç‚¹    
      - é¦™æ¸¯èŠ‚ç‚¹      
      - æ‰‹åŠ¨åˆ‡æ¢ 
      
  - name: æ²¹ç®¡è§†é¢‘
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies:
      - èŠ‚ç‚¹é€‰æ‹©
      - ä¸­è½¬åŠ é€Ÿ
      - ç›´è”èŠ‚ç‚¹    
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ¬§æ´²èŠ‚ç‚¹
      - ç¾æ´²èŠ‚ç‚¹
      - æ¾³æ´²èŠ‚ç‚¹
      - å…¶ä»–èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢ 
      
  - name: å¥ˆé£è§†é¢‘
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png
    type: select
    proxies:
      - èŠ‚ç‚¹é€‰æ‹©
      - ä¸­è½¬åŠ é€Ÿ
      - ç›´è”èŠ‚ç‚¹    
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ¬§æ´²èŠ‚ç‚¹
      - ç¾æ´²èŠ‚ç‚¹
      - æ¾³æ´²èŠ‚ç‚¹
      - å…¶ä»–èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢ 
      
  - name: å·´å“ˆå§†ç‰¹
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bahamut.png
    type: select
    proxies:
      - å°æ¹¾èŠ‚ç‚¹
      - èŠ‚ç‚¹é€‰æ‹©
      - æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
      
  - name: å“”å“©å“”å“©
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/bilibili.png
    type: select
    proxies:
      - å…¨çƒç›´è¿
      - å°æ¹¾èŠ‚ç‚¹
      - é¦™æ¸¯èŠ‚ç‚¹
      
  - name: å›½å¤–åª’ä½“
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/ForeignMedia.png
    type: select
    proxies:
      - èŠ‚ç‚¹é€‰æ‹©
      - æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
      
  - name: å›½å†…åª’ä½“
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/DomesticMedia.png
    type: select
    proxies:
      - DIRECT
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢
      
  - name: è°·æ­ŒFCM
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies:
      - DIRECT
      - èŠ‚ç‚¹é€‰æ‹©
      - ä¸­è½¬åŠ é€Ÿ
      - ç›´è”èŠ‚ç‚¹    
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ¬§æ´²èŠ‚ç‚¹
      - ç¾æ´²èŠ‚ç‚¹
      - æ¾³æ´²èŠ‚ç‚¹
      - å…¶ä»–èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢

  - name: å¾®è½¯äº‘ç›˜
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/OneDrive.png
    type: select
    proxies:
      - DIRECT
      - èŠ‚ç‚¹é€‰æ‹©
      - ä¸­è½¬åŠ é€Ÿ
      - ç›´è”èŠ‚ç‚¹    
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ¬§æ´²èŠ‚ç‚¹
      - ç¾æ´²èŠ‚ç‚¹
      - æ¾³æ´²èŠ‚ç‚¹
      - å…¶ä»–èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢
      
  - name: å¾®è½¯æœåŠ¡
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png
    type: select
    proxies:
      - DIRECT    
      - èŠ‚ç‚¹é€‰æ‹©
      - ä¸­è½¬åŠ é€Ÿ
      - ç›´è”èŠ‚ç‚¹    
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ¬§æ´²èŠ‚ç‚¹
      - ç¾æ´²èŠ‚ç‚¹
      - æ¾³æ´²èŠ‚ç‚¹
      - å…¶ä»–èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢
      
  - name: è‹¹æœæœåŠ¡
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png
    type: select
    proxies:
      - DIRECT    
      - èŠ‚ç‚¹é€‰æ‹©
      - ä¸­è½¬åŠ é€Ÿ
      - ç›´è”èŠ‚ç‚¹    
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ¬§æ´²èŠ‚ç‚¹
      - ç¾æ´²èŠ‚ç‚¹
      - æ¾³æ´²èŠ‚ç‚¹
      - å…¶ä»–èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢

  - name: æ¸¸æˆå¹³å°
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    type: select
    proxies:
      - DIRECT    
      - èŠ‚ç‚¹é€‰æ‹©
      - ä¸­è½¬åŠ é€Ÿ
      - ç›´è”èŠ‚ç‚¹    
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ¬§æ´²èŠ‚ç‚¹
      - ç¾æ´²èŠ‚ç‚¹
      - æ¾³æ´²èŠ‚ç‚¹
      - å…¶ä»–èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢  
      
  - name: å…¨çƒç›´è¿
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    type: select
    proxies:
      - DIRECT
      - èŠ‚ç‚¹é€‰æ‹©
      
  - name: å¹¿å‘Šæ‹¦æˆª
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png
    type: select
    proxies:
      - REJECT
      - DIRECT
      
  - name: åº”ç”¨å‡€åŒ–
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hijacking.png
    type: select
    proxies:
      - REJECT
      - DIRECT
      
  - name: æ¼ç½‘ä¹‹é±¼
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png
    type: select
    proxies:
      - DIRECT
      - èŠ‚ç‚¹é€‰æ‹©      
      
  - name: ä¸­è½¬åŠ é€Ÿ
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Rocket.png
    include-all: true
    filter: (?i)ğŸš€
    type: url-test
    interval: 300
    tolerance: 50
    
  - name: ç›´è”èŠ‚ç‚¹ 
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    include-all: true
    filter: (?i)ç›´è” 
    type: url-test
    interval: 300
    tolerance: 50
    
  - name: é¦™æ¸¯èŠ‚ç‚¹
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    include-all: true
    filter: (?i)æ¸¯|HK|hk|Hong Kong|HongKong|hongkong
    type: url-test
    interval: 300
    tolerance: 50

  - name: å°æ¹¾èŠ‚ç‚¹
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    include-all: true
    filter: (?i)å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan
    type: url-test
    interval: 300
    tolerance: 50
  - name: ç‹®åŸèŠ‚ç‚¹
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
    include-all: true
    filter: (?i)æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore
    type: url-test
    interval: 300
    tolerance: 50

  - name: æ—¥æœ¬èŠ‚ç‚¹
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    include-all: true
    filter: (?i)^(?!.*(è½åœ° HK JPåŠ é€Ÿ|HK JPåŠ é€Ÿ|HKJPåŠ é€Ÿ)).*(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan).*$
    type: url-test
    interval: 300
    tolerance: 50
    
  - name: ç¾å›½èŠ‚ç‚¹
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    include-all: true
    filter: (?i)ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|çº½çº¦|ä¸¹ä½›|ç›æ¹–åŸ
    type: url-test
    interval: 300
    tolerance: 50
    
  - name: ç¾æ´²èŠ‚ç‚¹ 
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/America_Map.png
    include-all: true
    filter: (?i)å—ç¾|é˜¿æ ¹å»·|å¸ƒå®œè¯ºæ–¯è‰¾åˆ©æ–¯|å·´è¥¿|åœ£ä¿ç½—|é‡Œçº¦|æ™ºåˆ©|åœ£åœ°äºšå“¥|ç§˜é²|åˆ©é©¬|AG|BZ|CH|å“¥ä¼¦æ¯”äºš|æ³¢å“¥å¤§|åŠ æ‹¿å¤§|CA|æ¸©å“¥å|å·´æ‹‰åœ­|å§”å†…ç‘æ‹‰
    type: url-test
    interval: 300
    tolerance: 50

  - name: æ¬§æ´²èŠ‚ç‚¹ 
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png
    include-all: true
    filter: (?i)æ¬§|æ¬§æ´²|è‹±å›½|ä¼¦æ•¦|åˆ©ç‰©æµ¦|æ³•å›½|å·´é»|é©¬èµ›|å¾·å›½|æŸæ—|æ…•å°¼é»‘|è¥¿ç­ç‰™|é©¬å¾·é‡Œ|æ„å¤§åˆ©|ç½—é©¬|ç±³å…°|GK|FR|GE|SP|IT|å†°å²›|è·å…°|å¢æ£®å ¡|LU|ä¹Œå…‹å…°|æ³¢å…°|è‘¡è„ç‰™|è¥¿ç­ç‰™|SP|æ¯”åˆ©æ—¶|ç‘å£«|èŠ¬å…°|ä¿åŠ åˆ©äºš|åŒˆç‰™åˆ©|åœŸè€³å…¶|ä»¥è‰²åˆ—
    type: url-test
    interval: 300
    tolerance: 50

  - name: æ¾³æ´²èŠ‚ç‚¹ 
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Australia.png
    include-all: true
    filter: (?i)æ¾³æ´²|æ¾³å¤§åˆ©äºš|æ‚‰å°¼|å¢¨å°”æœ¬|å¸ƒé‡Œæ–¯ç­|æ–°è¥¿å…°|å¥¥å…‹å…°|æƒ çµé¡¿|AU|NZ|æŸæ–¯
    type: url-test
    interval: 300
    tolerance: 50


  - name: å…¶ä»–èŠ‚ç‚¹
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    include-all: true
    filter: ^(?!.*(ğŸš€|ç›´è”|æ¸¯|HK|hk|Hong Kong|HongKong|hongkong)|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|çº½çº¦|ä¸¹ä½›|ç›æ¹–åŸ|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|å—ç¾|é˜¿æ ¹å»·|å¸ƒå®œè¯ºæ–¯è‰¾åˆ©æ–¯|å·´è¥¿|åœ£ä¿ç½—|é‡Œçº¦|æ™ºåˆ©|åœ£åœ°äºšå“¥|ç§˜é²|åˆ©é©¬|AG|BZ|CH|å“¥ä¼¦æ¯”äºš|æ³¢å“¥å¤§|åŠ æ‹¿å¤§|CA|æ¸©å“¥å|å·´æ‹‰åœ­|å§”å†…ç‘æ‹‰|æ¬§|æ¬§æ´²|è‹±å›½|ä¼¦æ•¦|åˆ©ç‰©æµ¦|æ³•å›½|å·´é»|é©¬èµ›|å¾·å›½|æŸæ—|æ…•å°¼é»‘|è¥¿ç­ç‰™|é©¬å¾·é‡Œ|æ„å¤§åˆ©|ç½—é©¬|ç±³å…°|GK|FR|GE|SP|IT|å†°å²›|è·å…°|å¢æ£®å ¡|LU|ä¹Œå…‹å…°|æ³¢å…°|è‘¡è„ç‰™|è¥¿ç­ç‰™|SP|æ¯”åˆ©æ—¶|ç‘å£«|èŠ¬å…°|ä¿åŠ åˆ©äºš|åŒˆç‰™åˆ©|åœŸè€³å…¶|ä»¥è‰²åˆ—|æ¾³æ´²|æ¾³å¤§åˆ©äºš|æ‚‰å°¼|å¢¨å°”æœ¬|å¸ƒé‡Œæ–¯ç­|æ–°è¥¿å…°|å¥¥å…‹å…°|æƒ çµé¡¿|AU|NZ|æŸæ–¯).*$
    type: url-test
    interval: 300
    tolerance: 50


rule-providers:
  LocalAreaNetwork:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/LocalAreaNetwork/LocalAreaNetwork.list
    path: ./ruleset/LocalAreaNetwork.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  UnBan:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/UnBan/UnBan.list
    path: ./ruleset/UnBan.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanAD:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/BanAD/BanAD.list
    path: ./ruleset/BanAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanProgramAD:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/BanProgramAD/BanProgramAD.list
    path: ./ruleset/BanProgramAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GoogleFCM:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/GoogleFCM/GoogleFCM.list
    path: ./ruleset/GoogleFCM.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GoogleCN:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/GoogleCN/GoogleCN.list
    path: ./ruleset/GoogleCN.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  SteamCN:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/SteamCN/SteamCN.list
    path: ./ruleset/SteamCN.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  OneDrive:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/OneDrive/OneDrive.list
    path: ./ruleset/OneDrive.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Microsoft:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Microsoft/Microsoft.list
    path: ./ruleset/Microsoft.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Apple:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Apple/Apple.list
    path: ./ruleset/Apple.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Telegram:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Telegram/Telegram.list
    path: ./ruleset/Telegram.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  OpenAI:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/OpenAI/OpenAI.list
    path: ./ruleset/OpenAI.list
    behavior: classical
    interval: 86400
    format: text
    type: http
    
  Copilot:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Copilot/Copilot.list
    path: ./ruleset/Copilot.listt
    behavior: classical
    interval: 86400
    format: text
    type: http   

  Claude:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Claude/Claude.list
    path: ./ruleset/Claude.list
    behavior: classical
    interval: 86400
    format: text
    type: http  

  Gemini:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Gemini/Gemini.list
    path: ./ruleset/Gemini.list
    behavior: classical
    interval: 86400
    format: text
    type: http  

  Epic:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Epic/Epic.list
    path: ./ruleset/Epic.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Origin:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Origin/Origin.list
    path: ./ruleset/Origin.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Sony:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Sony/Sony.list
    path: ./ruleset/Sony.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Steam:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Steam/Steam.list
    path: ./ruleset/Steam.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Nintendo:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Nintendo/Nintendo.list
    path: ./ruleset/Nintendo.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  YouTube:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/YouTube/YouTube.list
    path: ./ruleset/YouTube.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Netflix:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Netflix/Netflix.list
    path: ./ruleset/Netflix.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Bahamut:
    url: https://raw.githubusercontent.com/holddyxu/ClashRuleSet/main/Clash/Ruleset/Bahamut.list
    path: ./ruleset/Bahamut.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BilibiliHMT:
    url: https://raw.githubusercontent.com/holddyxu/ClashRuleSet/main/Clash/Ruleset/BilibiliHMT.list
    path: ./ruleset/BilibiliHMT.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaMedia:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/ChinaMedia/ChinaMedia.list
    path: ./ruleset/ChinaMedia.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyMedia:
    url: https://raw.githubusercontent.com/holddyxu/ClashRuleSet/main/Clash/ProxyMedia.list
    path: ./ruleset/ProxyMedia.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyGFWlist:
    url: https://raw.githubusercontent.com/holddyxu/ClashRuleSet/main/Clash/ProxyGFWlist.list
    path: ./ruleset/ProxyGFWlist.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaMax:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/ChinaMax/ChinaMax.yaml
    path: ./ruleset/ChinaMax.yaml
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaMax_Domain:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/ChinaMax/ChinaMax_Domain.yaml
    path: ./ruleset/ChinaMax_Domain.yaml
    behavior: domain
    interval: 86400
    format: text
    type: http
    
  ChinaMax_IP:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/ChinaMax/ChinaMax_IP.yaml
    path: ./ruleset/ChinaMax_IP.yaml
    behavior: ipcidr
    interval: 86400
    format: text
    type: http
  Download:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Download/Download.list
    path: ./ruleset/Download.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  PirateTrackers:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/PrivateTracker/PrivateTracker.list
    path: ./ruleset/PirateTrackers.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  JAV:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/JAV/JAV.list
    path: ./ruleset/JAV.list
    behavior: classical
    interval: 86400
    format: text
    type: http  
    

  ImgHostAbroad:
    url: https://raw.githubusercontent.com/holddyxu/ClashRuleSet/main/Clash/ImgHostAbroad/ImgHostAbroad.list
    path: ./ruleset/ImgHostAbroad.list 
    behavior: classical
    interval: 86400
    format: text
    type: http   
  
  Developer:
    url: https://raw.githubusercontent.com/holddyxu/clash/refs/heads/main/list/Developer/Developer.list
    path: ./ruleset/Developer.list
    behavior: classical
    interval: 86400
    format: text
    type: http    
    
  CiciAI:
    url: https://raw.githubusercontent.com/holddyxu/ClashRuleSet/main/Clash/Ruleset/CiciAi.list
    path: ./ruleset/PirateTrackers.list
    behavior: classical
    interval: 86400
    format: text
    type: http 

rules:
  - "RULE-SET,LocalAreaNetwork,å…¨çƒç›´è¿"
  - "RULE-SET,UnBan,å…¨çƒç›´è¿"
  - "RULE-SET,BanAD,å¹¿å‘Šæ‹¦æˆª"
  - "RULE-SET,BanProgramAD,åº”ç”¨å‡€åŒ–"
  - "RULE-SET,GoogleFCM,è°·æ­ŒFCM"
  - "RULE-SET,GoogleCN,å…¨çƒç›´è¿"
  - "RULE-SET,SteamCN,å…¨çƒç›´è¿"
  - "RULE-SET,OneDrive,å¾®è½¯äº‘ç›˜"
  - "RULE-SET,Microsoft,å¾®è½¯æœåŠ¡"
  - "RULE-SET,Apple,è‹¹æœæœåŠ¡"
  - "RULE-SET,Telegram,ç”µæŠ¥æ¶ˆæ¯"
  - "RULE-SET,OpenAI,OpenAI"
  - "RULE-SET,Copilot,OpenAI"  
  - "RULE-SET,Claude,ç¾å›½èŠ‚ç‚¹"  
  - "RULE-SET,Gemini,OpenAI"  
  - "RULE-SET,Epic,æ¸¸æˆå¹³å°"
  - "RULE-SET,Origin,æ¸¸æˆå¹³å°"
  - "RULE-SET,Sony,æ¸¸æˆå¹³å°"
  - "RULE-SET,Steam,æ¸¸æˆå¹³å°"
  - "RULE-SET,Nintendo,æ¸¸æˆå¹³å°"
  - "RULE-SET,YouTube,æ²¹ç®¡è§†é¢‘"
  - "RULE-SET,Netflix,å¥ˆé£è§†é¢‘"
  - "RULE-SET,Bahamut,å·´å“ˆå§†ç‰¹"
  - "RULE-SET,BilibiliHMT,å“”å“©å“”å“©"
  - "RULE-SET,Bilibili,å“”å“©å“”å“©"
  - "RULE-SET,ChinaMedia,å›½å†…åª’ä½“"
  - "RULE-SET,ProxyMedia,å›½å¤–åª’ä½“"
  - "RULE-SET,ProxyGFWlist,èŠ‚ç‚¹é€‰æ‹©"
  - "RULE-SET,ChinaMax,å…¨çƒç›´è¿"
  - "RULE-SET,ChinaMax_Domain,å…¨çƒç›´è¿"
  - "RULE-SET,ChinaMax_IP,å…¨çƒç›´è¿"
  - "RULE-SET,ChinaCompanyIp,å…¨çƒç›´è¿"
  - "RULE-SET,Download,å…¨çƒç›´è¿"
  - "GEOIP,CN,å…¨çƒç›´è¿"
  - "MATCH,æ¼ç½‘ä¹‹é±¼,å…¨çƒç›´è¿"
  - "RULE-SET,CiciAI,å…¨çƒç›´è¿"
  - "RULE-SET,Developer,èŠ‚ç‚¹é€‰æ‹©"
  - "RULE-SET,Developer,èŠ‚ç‚¹é€‰æ‹©"
  - "RULE-SET,ImgHostAbroad,èŠ‚ç‚¹é€‰æ‹©"
  - "RULE-SET,JAV,æ—¥æœ¬èŠ‚ç‚¹"
  - "RULE-SET,PirateTrackers,å…¨çƒç›´è¿"
